settings.outformat="pdf";
settings.prc=false;
settings.render=0;
import graph3;
unitsize(1cm);
currentprojection = orthographic(3,4,5);
real r=5;
usepackage("amsmath");
draw(O--0.7*r*Z, p=RGB(69,98,50)+linewidth(1pt), arrow=Arrow3(), L=Label("$r=\begin{pmatrix}0\\0\\rz\end{pmatrix}$", position=MidPoint));
draw(O--r*X, p=black+linewidth(1pt), arrow=Arrow3(TeXHead2), L=Label("$x$", position=EndPoint));
draw(O--r*Y, p=black+linewidth(1pt), arrow=Arrow3(TeXHead2), L=Label("$y$", position=EndPoint));
draw(O--r*Z, p=black+linewidth(1pt), arrow=Arrow3(TeXHead2), L=Label("$z$", position=EndPoint));
triple p1 = (3,4,4);
triple p2 = (5,0,4);
path3 arc = arc(c=(0,0,4),v1=p1,v2=p2);
draw(O--p1, p=black+linewidth(0.5pt), arrow=Arrow3(), L=Label("$p$", position=MidPoint));
draw(O--p2, p=black+linewidth(0.5pt), arrow=Arrow3(), L=Label("$p'$", position=MidPoint));
draw(arc, p=blue+linewidth(1pt), arrow=Arrow3(), L=Label("$\alpha$", position=MidPoint));
dot(p1,L=Label("$(x,y,z)$", align=S));
dot(p2,L=Label("$(x',y',z)$", align=N));
