settings.outformat="pdf";
settings.prc=false;
settings.render=0;
import graph3;
unitsize(1cm);
currentprojection = orthographic(3,4,5);
real r=5;
path3 myarc = rotate(18,Z) * Arc(c=O, normal=r*X, v1=-r*Z, v2=r*Z, n=10);
surface backHemisphere = surface(myarc, angle1=0, angle2=180, c=O, axis=Z);
surface frontHemisphere = surface(myarc, angle1=180, angle2=360, c=O, axis=Z);
draw(backHemisphere, surfacepen=material(white+opacity(0.2)));
draw(frontHemisphere, surfacepen=material(white+opacity(0.2)));
draw(O--1.5*r*X, p=black+linewidth(1pt), arrow=Arrow3(TeXHead2), L=Label("$x$", position=EndPoint));
draw(O--1.5*r*Y, p=black+linewidth(1pt), arrow=Arrow3(TeXHead2), L=Label("$y$", position=EndPoint));
draw(O--1.5*r*Z, p=black+linewidth(1pt), arrow=Arrow3(TeXHead2), L=Label("$z$", position=EndPoint));
draw(O--r*dir(30,65), p=RGB(69,98,50)+linewidth(1pt), arrow=Arrow3(), L=Label("$r$", position=MidPoint));
path3 arc1 = arc(c=O, v1=r*Z, v2=rotate(30,Y)*r*Z);
draw(arc1, p=blue+linewidth(1pt), arrow=Arrow3(), L=Label("$\theta$", position=MidPoint));
path3 arc2 = arc(c=(0,0,r*cos(pi/6)), v1=(r*sin(pi/6),0,r*cos(pi/6)), v2=rotate(65,Z)*(r*sin(pi/6),0,r*cos(pi/6)));
draw(arc2, p=red+linewidth(1pt), arrow=Arrow3(), L=Label("$\psi$", position=MidPoint));
